/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Carlos
 */
public class MenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form MenuGerente
     */
    public MenuGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrarGerente = new javax.swing.JButton();
        botaoCadastrarFuncionario = new javax.swing.JButton();
        botaoCadastrarProduto = new javax.swing.JButton();
        botaoCadastrarServico = new javax.swing.JButton();
        botaoCadastrarCliente = new javax.swing.JButton();
        botaoDesconectar = new javax.swing.JButton();
        menuGerente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCadastrarGerente.setBorder(null);
        botaoCadastrarGerente.setBorderPainted(false);
        botaoCadastrarGerente.setContentAreaFilled(false);
        botaoCadastrarGerente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botaoCadastrarGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 290, 40));

        botaoCadastrarFuncionario.setBorder(null);
        botaoCadastrarFuncionario.setBorderPainted(false);
        botaoCadastrarFuncionario.setContentAreaFilled(false);
        botaoCadastrarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botaoCadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 290, 40));

        botaoCadastrarProduto.setBorder(null);
        botaoCadastrarProduto.setBorderPainted(false);
        botaoCadastrarProduto.setContentAreaFilled(false);
        botaoCadastrarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botaoCadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 290, 40));

        botaoCadastrarServico.setBorder(null);
        botaoCadastrarServico.setBorderPainted(false);
        botaoCadastrarServico.setContentAreaFilled(false);
        botaoCadastrarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botaoCadastrarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 290, 40));

        botaoCadastrarCliente.setBorder(null);
        botaoCadastrarCliente.setBorderPainted(false);
        botaoCadastrarCliente.setContentAreaFilled(false);
        botaoCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botaoCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 290, 40));

        botaoDesconectar.setBorder(null);
        botaoDesconectar.setBorderPainted(false);
        botaoDesconectar.setContentAreaFilled(false);
        botaoDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 130, 30));

        menuGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu_gerente.png"))); // NOI18N
        getContentPane().add(menuGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(700, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesconectarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarCliente;
    private javax.swing.JButton botaoCadastrarFuncionario;
    private javax.swing.JButton botaoCadastrarGerente;
    private javax.swing.JButton botaoCadastrarProduto;
    private javax.swing.JButton botaoCadastrarServico;
    private javax.swing.JButton botaoDesconectar;
    private javax.swing.JLabel menuGerente;
    // End of variables declaration//GEN-END:variables
}
