/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Carlos
 */
public class MenuFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form MenuFuncionario
     */
    public MenuFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrarCliente = new javax.swing.JButton();
        botaoFazerAgendamento = new javax.swing.JButton();
        botaoFinalizarAtendimento = new javax.swing.JButton();
        botaoDesconectar = new javax.swing.JButton();
        menuFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoCadastrarCliente.setBorder(null);
        botaoCadastrarCliente.setBorderPainted(false);
        botaoCadastrarCliente.setContentAreaFilled(false);
        botaoCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botaoCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, 40));

        botaoFazerAgendamento.setBorder(null);
        botaoFazerAgendamento.setBorderPainted(false);
        botaoFazerAgendamento.setContentAreaFilled(false);
        botaoFazerAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botaoFazerAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 290, 40));

        botaoFinalizarAtendimento.setBorder(null);
        botaoFinalizarAtendimento.setBorderPainted(false);
        botaoFinalizarAtendimento.setContentAreaFilled(false);
        botaoFinalizarAtendimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botaoFinalizarAtendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 290, 40));

        botaoDesconectar.setBorder(null);
        botaoDesconectar.setBorderPainted(false);
        botaoDesconectar.setContentAreaFilled(false);
        botaoDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 130, 30));

        menuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu_funcionario.png"))); // NOI18N
        getContentPane().add(menuFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(700, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesconectarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarCliente;
    private javax.swing.JButton botaoDesconectar;
    private javax.swing.JButton botaoFazerAgendamento;
    private javax.swing.JButton botaoFinalizarAtendimento;
    private javax.swing.JLabel menuFuncionario;
    // End of variables declaration//GEN-END:variables
}
