package telas;

import classes.Funcionario;
import classes.Gerente;
import javax.swing.JOptionPane;
import telas.MenuFuncionario;

/**
 *
 * @author ARTHUR HENRIQUE
 */
public class TelaLogin extends javax.swing.JFrame {

    public static String senhaGerente = "admin";
    public static String cpfGerente = "00000000000";
    public static String nome = "";
    public static String email = "email@email.com";
    public static String celular = "40028922";
    public static String endereco = "unb";
    public static Gerente gerente = new Gerente(nome, cpfGerente, email, endereco, celular, senhaGerente);

    public boolean verificarCpf(String CPF) {
        for (Funcionario funcionario : CadastroFuncionario.Funcionarios) {
            if (funcionario.getCPF().equals(CPF)) {
                return true;
            }
        }
        return false;
    }

    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCpf = new javax.swing.JFormattedTextField();
        campoSenha = new javax.swing.JPasswordField();
        botaoAcessar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        telaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoCpf.setBackground(new java.awt.Color(0, 173, 181));
        campoCpf.setBorder(null);
        campoCpf.setForeground(new java.awt.Color(238, 238, 238));
        try {
            campoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, 30));

        campoSenha.setBackground(new java.awt.Color(0, 173, 181));
        campoSenha.setForeground(new java.awt.Color(238, 238, 238));
        campoSenha.setBorder(null);
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, 30));

        botaoAcessar.setForeground(new java.awt.Color(255, 255, 255));
        botaoAcessar.setBorder(null);
        botaoAcessar.setBorderPainted(false);
        botaoAcessar.setContentAreaFilled(false);
        botaoAcessar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, 40));

        botaoSair.setBorder(null);
        botaoSair.setBorderPainted(false);
        botaoSair.setContentAreaFilled(false);
        botaoSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 100, 40));

        telaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_login.png"))); // NOI18N
        getContentPane().add(telaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 687, 467));

        setSize(new java.awt.Dimension(688, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcessarActionPerformed
        // TODO add your handling code here:
        if (campoCpf.getText().equals(cpfGerente) && campoSenha.getText().equals(senhaGerente)) {
            MenuGerente menuGerente = new MenuGerente();
            menuGerente.setVisible(true);
            this.dispose();
        } else if (verificarCpf(campoCpf.getText())) {  //verifica se o cpf digitado corresponde com algum funcionario
            new MenuFuncionario().setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "CPF ou senha incorretos. Por favor, tente novamente.");
        }
    }//GEN-LAST:event_botaoAcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAcessar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JFormattedTextField campoCpf;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel telaLogin;
    // End of variables declaration//GEN-END:variables
}
